# default can be INFO/WARN/ERROR/OFF
org.slf4j.simpleLogger.defaultLogLevel=info

# Silence Exposed logger categories
org.slf4j.simpleLogger.log.Exposed=error
org.slf4j.simpleLogger.log.org.jetbrains.exposed=error

# Silence Hikari
org.slf4j.simpleLogger.log.com.zaxxer.hikari=warn
org.slf4j.simpleLogger.log.com.zaxxer.hikari.HikariDataSource=warn
org.slf4j.simpleLogger.log.com.zaxxer.hikari.pool=warn
