# default can be INFO/WARN/ERROR/OFF
org.slf4j.simpleLogger.defaultLogLevel=info

# Silence Exposed logger categories
org.slf4j.simpleLogger.log.Exposed=error
org.slf4j.simpleLogger.log.org.jetbrains.exposed=error
